# Build docker image on push to feature/* branch

name: Docker Build Feature Branch

on:
  push:
    branches: 
      - 'feature/**'
    paths:
      - 'Dockerfile'
      
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag halflogic/tf-eks-toolbox:$(date +%s)
