# Build and push docker image on new release creation

name: Docker Build Push Release

on:
  release:
    # Only use the types keyword to narrow down the activity types that will trigger your workflow.
    types: [published, edited]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set Tag Name
        run: |
          echo $GITHUB_REF
          echo "TAG_NAME=${GITHUB_REF/'refs/tags/'/}" >> $GITHUB_ENV

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: halflogic/tf-eks-toolbox:${{ env.TAG_NAME }}, halflogic/tf-eks-toolbox:latest
          
